# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', models.ImageField(blank=True, default='cliente/no_foto.jpg', null=True, upload_to='cliente/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            managers=[
                ('cliente', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('numeroDoc', models.DecimalField(decimal_places=2, default=0, max_digits=15, primary_key='True', serialize=False, verbose_name='N\xfamero Documento')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo Documento')),
                ('emissao', models.DateField(verbose_name='Emiss\xe3o')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('docAtivo', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('descricaoEmail', models.CharField(max_length=100, verbose_name='Descir\xe7\xe3o do Email')),
                ('emailAtivo', models.BooleanField(verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cep', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='CEP')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descri\xe7\xe3o')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('numero', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='N\xfamero')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='numeroDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joane.Documento'),
        ),
    ]
