# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('joane', '0002_auto_20160521_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDocumento',
            fields=[
                ('fnumeroDoc', models.DecimalField(decimal_places=2, default=0, max_digits=15, primary_key='True', serialize=False, verbose_name='N\xfamero Documento')),
                ('ftipo', models.CharField(max_length=100, verbose_name='Tipo Documento')),
                ('femissao', models.DateField(verbose_name='Emiss\xe3o')),
                ('fvencimento', models.DateField(verbose_name='Vencimento')),
                ('fdocAtivo', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='FEmail',
            fields=[
                ('fdescricaoEmail', models.CharField(max_length=100, verbose_name='Descir\xe7\xe3o do Email')),
                ('femailAtivo', models.BooleanField(verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FEndereco',
            fields=[
                ('fcep', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='CEP')),
                ('ftipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('fdescricao', models.CharField(max_length=300, verbose_name='Descri\xe7\xe3o')),
                ('fcomplemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('fnumero', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='N\xfamero')),
                ('fativo', models.BooleanField(verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='fornecedor',
            managers=[
                ('fornecedor', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome',
            new_name='fnome',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ffoto',
            field=models.ImageField(blank=True, default='cliente/no_foto.jpg', null=True, upload_to='fornecedor/'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fendereco',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joane.Fornecedor'),
        ),
        migrations.AddField(
            model_name='femail',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joane.Fornecedor'),
        ),
        migrations.AddField(
            model_name='fdocumento',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joane.Fornecedor'),
        ),
    ]
